# Generated by Django 4.2.29 on 2026-03-31 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='past_papers/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_papers', to='notes.subject')),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
    ]
