# Generated by Django 4.2.29 on 2026-03-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='source_file',
            field=models.FileField(blank=True, upload_to='contributions/notes/'),
        ),
    ]
